### ISSUE TITLE
Question: On the GEOM Dataset availability

### ISSUE THREAD

**Issue by Daasin** [PattanaikL/GeoMol#3]
Would the referenced dataset located at https://dataverse.harvard.edu/api/access/datafile/4327252 also be available to access under a F/OSS-Compliant license? And is it accessible by any other means or mirrors?

**Comment by PattanaikL** [comment]
I'm not sure. I suggest contacting Simon, the first author of the GEOM paper (saxelrod@mit.edu). He said he'd be willing to help answer your question!
